### ISSUE TITLE
Error in back navigation event from a page not registered in the SideDrawer

### ISSUE THREAD

**Issue by alexmeia** [NativeScript/template-drawer-navigation-ts#52]
Hello,
I needed a subsection of the main navigation and created o folder inside the _browse_ folder with its page, controller and model. The section is intended to show a detail page for the element in the main section, following the pattern implemented in  [Master Detail Template](https://github.com/NativeScript/template-master-detail-ts).
The navigation to the detail page works fine using the `topmost.navigate()` method, but when I try to go back to the main section using `topmost.goBack();` or the Android back button I receive this error:

```
System.err: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to com.telerik.android.primitives.widget.sidedrawer.SideDrawerState
System.err:     at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onRestoreInstanceState(RadSideDrawer.java:784)
System.err:     at android.view.View.dispatchRestoreInstanceState(View.java:17445)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3693)
System.err:     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3699)
System.err:     at android.view.View.restoreHierarchyState(View.java:17423)
System.err:     at android.app.Fragment.restoreViewState(Fragment.java:653)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
System.err:     at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1547)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1609)
System.err:     at android.app.BackStackRecord.executePopOps(BackStackRecord.java:865)
System.err:     at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2389)
System.err:     at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2187)
System.err:     at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2140)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2047)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
System.err:     at android.os.Handler.handleCallback(Handler.java:769)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6540)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

The same error occurs in all Android devices and emulators that I have tested (Nexus 5, Nexus 6P, Huawei P10).
TNS Core Modules and NativeScript Pro UI are both at version 3.2.0.

**Comment by alexmeia** [comment]
Actually, the problem is not directly related to this template or to RadSideDrawer component.
It seems a compatibility issue between RadSideDrawer and [nativescript-google-maps-sdk plugin](https://github.com/dapriett/nativescript-google-maps-sdk). The problem occurs only in the pages where this plugin is used. 
I published this basic app to highlight the issue: https://github.com/alexmeia/nativescritp-sidedrawer-and-googlemaps

**Comment by NickIliev** [comment]
This issue was moved to telerik/nativescript-ui-feedback#433
